name = "Better Content"
version = "Playtest v2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89062853d4551accb9130958ac14f1f9fe4ae2d0d2f012878635ae938e9d178a"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
