name = "Better Content"
version = "Playtest v4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dde94bbfe30868c9baff4b4bfe76875b42d47e062338e8048a499046a8a6db11"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
