name = "Bound to Matter"
version = "Playtest 3 - v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa53cd02b135a768a663d56b9af8a1880c562409412346e41e00dd8d80bf4d53"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["forge"]
