#A list of block IDs and tags that should be affected by this definition.
#Entries can be supplied in the below formats:
#	Namespaces:   '<minecraft>'
#	Tags:         '#forge:stone'
#	IDs:          'minecraft:stone'
Blocks = [
	"ae2:chiseled_quartz_wall",
	"ae2:cut_quartz_wall",
	"ae2:fluix_wall",
	"ae2:quartz_brick_wall",
	"ae2:quartz_pillar_wall",
	"ae2:quartz_wall",
	"ae2:smooth_quartz_wall",
	"aether:aerogel_wall",
	"aether:angelic_wall",
	"aether:carved_wall",
	"aether:hellfire_wall",
	"aether:holystone_brick_wall",
	"aether:holystone_wall",
	"aether:icestone_wall",
	"aether:mossy_holystone_wall",
	"bloodmagic:dungeon_brick1_wall",
	"bloodmagic:dungeon_polished_wall",
	"bloodmagic:dungeon_stone_wall",
	"bloodmagic:dungeon_tile_wall",
	"burnt:sooty_andesite_wall",
	"burnt:sooty_brick_wall",
	"burnt:sooty_cobblestone_wall",
	"burnt:sooty_diorite_wall",
	"burnt:sooty_granite_wall",
	"burnt:sooty_mossy_cobblestone_wall",
	"burnt:sooty_mossy_stone_brick_wall",
	"burnt:sooty_mud_brick_wall",
	"burnt:sooty_stone_brick_wall",
	"create:cut_andesite_brick_wall",
	"create:cut_andesite_wall",
	"create:cut_asurine_brick_wall",
	"create:cut_asurine_wall",
	"create:cut_calcite_brick_wall",
	"create:cut_calcite_wall",
	"create:cut_crimsite_brick_wall",
	"create:cut_crimsite_wall",
	"create:cut_deepslate_brick_wall",
	"create:cut_deepslate_wall",
	"create:cut_diorite_brick_wall",
	"create:cut_diorite_wall",
	"create:cut_dripstone_brick_wall",
	"create:cut_dripstone_wall",
	"create:cut_granite_brick_wall",
	"create:cut_granite_wall",
	"create:cut_limestone_brick_wall",
	"create:cut_limestone_wall",
	"create:cut_ochrum_brick_wall",
	"create:cut_ochrum_wall",
	"create:cut_scorchia_brick_wall",
	"create:cut_scorchia_wall",
	"create:cut_scoria_brick_wall",
	"create:cut_scoria_wall",
	"create:cut_tuff_brick_wall",
	"create:cut_tuff_wall",
	"create:cut_veridium_brick_wall",
	"create:cut_veridium_wall",
	"create:polished_cut_andesite_wall",
	"create:polished_cut_asurine_wall",
	"create:polished_cut_calcite_wall",
	"create:polished_cut_crimsite_wall",
	"create:polished_cut_deepslate_wall",
	"create:polished_cut_diorite_wall",
	"create:polished_cut_dripstone_wall",
	"create:polished_cut_granite_wall",
	"create:polished_cut_limestone_wall",
	"create:polished_cut_ochrum_wall",
	"create:polished_cut_scorchia_wall",
	"create:polished_cut_scoria_wall",
	"create:polished_cut_tuff_wall",
	"create:polished_cut_veridium_wall",
	"create:small_andesite_brick_wall",
	"create:small_asurine_brick_wall",
	"create:small_calcite_brick_wall",
	"create:small_crimsite_brick_wall",
	"create:small_deepslate_brick_wall",
	"create:small_diorite_brick_wall",
	"create:small_dripstone_brick_wall",
	"create:small_granite_brick_wall",
	"create:small_limestone_brick_wall",
	"create:small_ochrum_brick_wall",
	"create:small_scorchia_brick_wall",
	"create:small_scoria_brick_wall",
	"create:small_tuff_brick_wall",
	"create:small_veridium_brick_wall",
	"createdeco:blue_brick_wall",
	"createdeco:corner_blue_brick_wall",
	"createdeco:corner_dean_brick_wall",
	"createdeco:corner_dusk_brick_wall",
	"createdeco:corner_pearl_brick_wall",
	"createdeco:corner_red_brick_wall",
	"createdeco:corner_scarlet_brick_wall",
	"createdeco:corner_umber_brick_wall",
	"createdeco:corner_verdant_brick_wall",
	"createdeco:cracked_blue_brick_wall",
	"createdeco:cracked_dean_brick_wall",
	"createdeco:cracked_dusk_brick_wall",
	"createdeco:cracked_pearl_brick_wall",
	"createdeco:cracked_red_brick_wall",
	"createdeco:cracked_scarlet_brick_wall",
	"createdeco:cracked_umber_brick_wall",
	"createdeco:cracked_verdant_brick_wall",
	"createdeco:dean_brick_wall",
	"createdeco:dusk_brick_wall",
	"createdeco:long_blue_brick_wall",
	"createdeco:long_dean_brick_wall",
	"createdeco:long_dusk_brick_wall",
	"createdeco:long_pearl_brick_wall",
	"createdeco:long_red_brick_wall",
	"createdeco:long_scarlet_brick_wall",
	"createdeco:long_umber_brick_wall",
	"createdeco:long_verdant_brick_wall",
	"createdeco:mossy_blue_brick_wall",
	"createdeco:mossy_dean_brick_wall",
	"createdeco:mossy_dusk_brick_wall",
	"createdeco:mossy_pearl_brick_wall",
	"createdeco:mossy_red_brick_wall",
	"createdeco:mossy_scarlet_brick_wall",
	"createdeco:mossy_umber_brick_wall",
	"createdeco:mossy_verdant_brick_wall",
	"createdeco:pearl_brick_wall",
	"createdeco:scarlet_brick_wall",
	"createdeco:short_blue_brick_wall",
	"createdeco:short_dean_brick_wall",
	"createdeco:short_dusk_brick_wall",
	"createdeco:short_pearl_brick_wall",
	"createdeco:short_red_brick_wall",
	"createdeco:short_scarlet_brick_wall",
	"createdeco:short_umber_brick_wall",
	"createdeco:short_verdant_brick_wall",
	"createdeco:tiled_blue_brick_wall",
	"createdeco:tiled_dean_brick_wall",
	"createdeco:tiled_dusk_brick_wall",
	"createdeco:tiled_pearl_brick_wall",
	"createdeco:tiled_red_brick_wall",
	"createdeco:tiled_scarlet_brick_wall",
	"createdeco:tiled_umber_brick_wall",
	"createdeco:tiled_verdant_brick_wall",
	"createdeco:umber_brick_wall",
	"createdeco:verdant_brick_wall",
	"deeperdarker:cobbled_gloomslate_wall",
	"deeperdarker:cobbled_sculk_stone_wall",
	"deeperdarker:cut_gloomslate_wall",
	"deeperdarker:cut_sculk_stone_wall",
	"deeperdarker:gloomslate_brick_wall",
	"deeperdarker:gloomslate_tile_wall",
	"deeperdarker:gloomslate_wall",
	"deeperdarker:polished_gloomslate_wall",
	"deeperdarker:polished_sculk_stone_wall",
	"deeperdarker:sculk_grime_brick_wall",
	"deeperdarker:sculk_stone_brick_wall",
	"deeperdarker:sculk_stone_tile_wall",
	"deeperdarker:sculk_stone_wall",
	"deeperdarker:smooth_gloomslate_wall",
	"deeperdarker:smooth_sculk_stone_wall",
	"fallout_wastelands_:adobe_block_wall",
	"fallout_wastelands_:base_wall",
	"fallout_wastelands_:bo_s_steel_wall",
	"fallout_wastelands_:cracked_wasteland_concrete_wall",
	"fallout_wastelands_:double_scaffold_wall",
	"fallout_wastelands_:dried_planks_wall",
	"fallout_wastelands_:facility_wall",
	"fallout_wastelands_:military_metal_plate_wall",
	"fallout_wastelands_:oxidized_metal_wall",
	"fallout_wastelands_:roof_metal_wall",
	"fallout_wastelands_:rusted_sheet_metal_wall",
	"fallout_wastelands_:vault_wall",
	"fallout_wastelands_:wasteland_brick_wall",
	"fallout_wastelands_:wasteland_concrete_wall",
	"immersive_weathering:cracked_brick_wall",
	"immersive_weathering:cracked_deepslate_brick_wall",
	"immersive_weathering:cracked_deepslate_tile_wall",
	"immersive_weathering:cracked_end_stone_brick_wall",
	"immersive_weathering:cracked_nether_brick_wall",
	"immersive_weathering:cracked_polished_blackstone_brick_wall",
	"immersive_weathering:cracked_prismarine_brick_wall",
	"immersive_weathering:cracked_stone_brick_wall",
	"immersive_weathering:dark_prismarine_wall",
	"immersive_weathering:mossy_brick_wall",
	"immersive_weathering:mossy_stone_wall",
	"immersive_weathering:prismarine_brick_wall",
	"immersive_weathering:sandy_cobblestone_wall",
	"immersive_weathering:sandy_stone_brick_wall",
	"immersive_weathering:sandy_stone_wall",
	"immersive_weathering:snowy_cobblestone_wall",
	"immersive_weathering:snowy_stone_brick_wall",
	"immersive_weathering:snowy_stone_wall",
	"immersive_weathering:stone_wall",
	"natures_spirit:chert_brick_wall",
	"natures_spirit:chert_tile_wall",
	"natures_spirit:cobbled_travertine_wall",
	"natures_spirit:mossy_cobbled_travertine_wall",
	"natures_spirit:mossy_travertine_brick_wall",
	"natures_spirit:pink_sandstone_wall",
	"natures_spirit:polished_chert_wall",
	"natures_spirit:polished_travertine_wall",
	"natures_spirit:travertine_brick_wall",
	"natures_spirit:travertine_tile_wall",
	"notreepunching:andesite_cobblestone_wall",
	"notreepunching:diorite_cobblestone_wall",
	"notreepunching:granite_cobblestone_wall",
	"pneumaticcraft:compressed_brick_wall",
	"pneumaticcraft:pressure_chamber_wall",
	"pneumaticcraft:reinforced_brick_wall",
	"quark:andesite_bricks_wall",
	"quark:blackstone_bricks_wall",
	"quark:blue_nether_bricks_wall",
	"quark:calcite_bricks_wall",
	"quark:calcite_wall",
	"quark:cobblestone_bricks_wall",
	"quark:diorite_bricks_wall",
	"quark:dirt_bricks_wall",
	"quark:dripstone_block_wall",
	"quark:dripstone_bricks_wall",
	"quark:granite_bricks_wall",
	"quark:jasper_bricks_wall",
	"quark:jasper_wall",
	"quark:limestone_bricks_wall",
	"quark:limestone_wall",
	"quark:mossy_cobblestone_bricks_wall",
	"quark:myalite_bricks_wall",
	"quark:myalite_wall",
	"quark:netherrack_bricks_wall",
	"quark:paper_wall",
	"quark:permafrost_bricks_wall",
	"quark:permafrost_wall",
	"quark:raw_copper_bricks_wall",
	"quark:raw_gold_bricks_wall",
	"quark:raw_iron_bricks_wall",
	"quark:red_sandstone_bricks_wall",
	"quark:sandstone_bricks_wall",
	"quark:shale_bricks_wall",
	"quark:shale_wall",
	"quark:soul_sandstone_bricks_wall",
	"quark:soul_sandstone_wall",
	"quark:tuff_bricks_wall",
	"quark:tuff_wall",
	"savage_and_ravage:gloomy_tile_wall",
	"tconstruct:seared_bricks_wall",
	"tconstruct:seared_cobble_wall",
	"undergarden:depthrock_brick_wall",
	"undergarden:depthrock_wall",
	"undergarden:polished_depthrock_wall",
	"undergarden:shiverstone_brick_wall",
	"undergarden:shiverstone_wall",
	"undergarden:tremblecrust_brick_wall",
	"undergarden:tremblecrust_wall",
	"unearthed:beige_limestone_brick_wall",
	"unearthed:beige_limestone_wall",
	"unearthed:cobbled_beige_limestone_wall",
	"unearthed:cobbled_grey_limestone_wall",
	"unearthed:cobbled_limestone_wall",
	"unearthed:cobbled_phyllite_wall",
	"unearthed:cobbled_slate_wall",
	"unearthed:conglomerate_wall",
	"unearthed:cut_mudstone_wall",
	"unearthed:cut_siltstone_wall",
	"unearthed:dolerite_wall",
	"unearthed:dolomite_wall",
	"unearthed:gabbro_wall",
	"unearthed:granodiorite_wall",
	"unearthed:grey_limestone_brick_wall",
	"unearthed:grey_limestone_wall",
	"unearthed:kimberlite_wall",
	"unearthed:lignite_wall",
	"unearthed:limestone_brick_wall",
	"unearthed:limestone_wall",
	"unearthed:marble_wall",
	"unearthed:mossy_cobbled_phyllite_wall",
	"unearthed:mossy_cobbled_slate_wall",
	"unearthed:mossy_phyllite_brick_wall",
	"unearthed:mossy_slate_brick_wall",
	"unearthed:mudstone_wall",
	"unearthed:phyllite_brick_wall",
	"unearthed:phyllite_wall",
	"unearthed:pillow_basalt_wall",
	"unearthed:polished_conglomerate_wall",
	"unearthed:polished_dolomite_wall",
	"unearthed:polished_gabbro_brick_wall",
	"unearthed:polished_gabbro_wall",
	"unearthed:polished_granodiorite_brick_wall",
	"unearthed:polished_granodiorite_wall",
	"unearthed:polished_rhyolite_brick_wall",
	"unearthed:polished_rhyolite_wall",
	"unearthed:polished_white_granite_brick_wall",
	"unearthed:polished_white_granite_wall",
	"unearthed:pumice_wall",
	"unearthed:quartzite_wall",
	"unearthed:rhyolite_wall",
	"unearthed:siltstone_wall",
	"unearthed:slate_brick_wall",
	"unearthed:slate_wall",
	"unearthed:weathered_rhyolite_wall",
	"unearthed:white_granite_wall",
]

[Physics]
	#The maximum weight the block(s) can support both horizontally and vertically.
	#Range: > 0
	SupportStrength = 66020

	#Additional support strength to apply to the amount of weight the block(s) can support above when acting as a beam.
	#A value of 1.0 will allow the block(s) to support an infinite amount of weight, whereas a value of 0.0 will not apply any additional strengthening.
	#Range: 0.0 ~ 1.0
	BeamStrength = 0.9

	#The mass of the block(s), in kilograms.
	#Range: 1.0 ~ 50000.0
	Mass = 900.0

	#Whether the block(s) can hang from other blocks for support.
	CanHang = true

	#Whether the block(s) can attach to the sides of other blocks for support.
	CanAttach = true

	#Whether the block(s) can diagonally attach to other blocks for support.
	CanAttachDiagonally = true

	#The chance the block(s) will slide after falling and landing.
	#Range: 0.0 ~ 1.0
	SlideChance = 0.5

	#An additional "dice roll" to apply to the base slide chance of the block(s), when being placed by an entity.
	#Setting a value of 1.0 means the slide chance will remain unaffected.
	#Range: 0.0 ~ 1.0
	PlacementSlideModifier = 0.0

	#A multiplier to apply to the damage caused by the block(s) when falling on entities.
	#Range: 0.0 ~ 10.0
	EntityDamageScale = 1.0

	#Whether the block(s) should break instead of falling.
	BreaksOnFalling = false

	#The maximum force the block(s) can withstand before being broken.
	#Range: > 0
	Strength = 586800

	#Whether the block(s) can be supported by liquids that are below.
	FloatsOnLiquid = false

	#This section allows you to extend the collision bounds for each specific face of the block(s).
	#Note: Directions are relative to the orientation of the block(s) (excluding vertical axis), not the world itself.
	[Physics.ExtendedCollisionBounds]
		#Fully extends the collision bounds of the block(s) in the UP direction.
		Up = false

		#Fully extends the collision bounds of the block(s) in the DOWN direction.
		Down = false

		#Fully extends the collision bounds of the block(s) in the NORTH direction.
		North = false

		#Fully extends the collision bounds of the block(s) in the EAST direction.
		East = false

		#Fully extends the collision bounds of the block(s) in the SOUTH direction.
		South = false

		#Fully extends the collision bounds of the block(s) in the WEST direction.
		West = false

[ChunkAnalysis]
	#Whether the block(s) should be processed during chunk analysis updates.
	Enabled = true
